import type { Metadata } from "next";
import { Inter, Mulish } from "next/font/google";
import "./globals.scss";
import { ThemeProvider } from 'next-themes'

const mulish = Mulish({ 
  subsets: ["latin"],
  display: 'swap',
  variable: '--font-mulish',
})

export const metadata: Metadata = {
  title: "OneClickDrive Admin",
  // description: "Generated by create next app",
  icons: {
    icon: '/favicon.ico',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={mulish.className}>
        <ThemeProvider attribute="class">
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
